# Generated by Django 4.1 on 2022-08-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_ht',
            new_name='total_price',
        ),
    ]
