# Generated by Django 4.1 on 2022-08-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantiles',
            new_name='quantity',
        ),
    ]
