# Generated by Django 4.1 on 2022-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_quantiles_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amaount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
