# Generated by Django 4.1 on 2022-09-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_order_id_order_payment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='payment_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
