# Generated by Django 4.1 on 2022-09-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_order_id_order_payment_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_track_id',
        ),
    ]
