# Generated by Django 4.1 on 2022-09-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
